# Default security package

[description]
version_format=7
version=1.0.0.1

[cybersecurity_cfg]
access_control_selection=2
local_access_control_enabled=true
USB_port_enabled=true
local_maintenance_port_enabled=true
signature_check_enabled=false
nac_supplicant_portcontrol=false

[https]
pem_file=nginx_cert.crt
private_key_file=nginx_key.pem

[users]
# Wabtec_12380asdfugQWe
Maintainer_hashed_passwd=$5$qO0ptzAk1Vd4.YCS$UFsQBdiclMpApCCkiDyufUKcgKXP6aaKyF4LbgPKdd7
# Wabtec_sdakjfh328912v
ServiceEng_hashed_passwd=$5$QPLmLsGf3IL4UY9I$qizazcMCrzvO3lainrfiYIlaY9zGzRuRx8UbAwyU359
# Wabtec_7ihribodcd8922
ProdEng_hashed_passwd=$5$M2OPKdcDaxq4yU.z$URNi.tp4UO6AgGzPlPcKA.4aoPR95Py3TWXzEEbbEZ7
# Wabtec_78yadvb32ohsdf
Admin_hashed_passwd=$5$8pxhUOK836Y2.SMd$Vdz7bXeVz4L8ICL/rR.MhlW3hPbdMM2yrlmYZQ8gQ06

[authentication]
server_address=
pre_shared_key=

[log1]
server_address=

[log2]
server_address=

[account]
non_locking_failed_access_number=10
locked_account_time_sec=30

[maint]
session_idle_expiration_time_sec=600

[Cybersecurity_check_parameters]
server_check=false

[files_https]
private=files/https/private/nginx_key.pem
certificate=files/https/certificate/nginx_cert.crt

[files_system_use_notification]
system_use_notification=files/files_system_use_notification/dummy.txt
